if (/*@cc_on!@*/false || (!!window.MSInputMethodContext && !!document.documentMode)){
var lang = navigator.language||navigator.userLanguage;
langtwo = lang.substr(0, 2);

//Chinese
if(langtwo == 'zh'){ if(lang == 'zh-Hant' || lang == 'zh-TW' || lang == 'zh-tw'){window.location.href="https://www.performasports.tv/update-your-browser";}
 else{window.location.href="https://www.performasports.tv/update-your-browser";}
                   }
//else
else if(langtwo == 'af'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sq'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'am'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ar'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'hy'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'az'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'eu'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'be'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'bn'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'bs'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'bg'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ca'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ce'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'co'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'hr'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'cs'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'da'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'nl'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'eo'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'et'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'fi'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'fr'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'fy'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'gl'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ka'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'de'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'el'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'gu'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ht'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ha'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo=='he' || langtwo=='iw'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'hi'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'hm'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'hu'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'is'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ig'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'id'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ga'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'it'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ja'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'jv'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'kn'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'kk'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'km'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'rw'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ko'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ku'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ky'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'lo'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'la'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'lv'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'lt'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'lb'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'mk'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'mg'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ms'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ml'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'mt'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'mi'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'mr'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'mn'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'my'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ne'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'no'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ny'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'or'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ps'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'fa'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'pl'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'pt'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'pa'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ro'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ru'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sm'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'gd'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sr'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'st'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sn'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sd'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'si'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sk'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sl'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'so'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'es'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'su'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sw'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'sv'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'tl'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'tg'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ta'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'tt'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'te'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'th'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'tr'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'tk'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'uk'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ur'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'ug'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'uz'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'vi'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'cy'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'xh'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'yi'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'yo'){window.location.href="https://www.performasports.tv/update-your-browser";}
else if(langtwo == 'zu'){window.location.href="https://www.performasports.tv/update-your-browser";}

else if(lang == 'haw'){window.location.href="https://www.performasports.tv/update-your-browser";}
//else English
 else{window.location.href="https://www.performasports.tv/update-your-browser";}}
