if (/*@cc_on!@*/false || (!!window.MSInputMethodContext && !!document.documentMode)){
var lang = navigator.language||navigator.userLanguage;
langtwo = lang.substr(0, 2);

//Chinese
if(langtwo == 'zh'){ if(lang == 'zh-Hant' || lang == 'zh-TW' || lang == 'zh-tw'){window.location.href="https://www.performasports.tv/update-your-browser/";}
 else{window.location.href="https://www.performasports.tv/update-your-browser/";}
                   }
//else
else if(langtwo == 'af'){window.location.href="https://www.performasports.tv/update-your-browser/";}
else if(langtwo == 'sq'){window.location.href="https://www.performasports.tv/update-your-browser/";}
else if(langtwo == 'am'){window.location.href="https://www.performasports.tv/update-your-browser/";}
else if(langtwo == 'ar'){window.location.href="https://www.performasports.tv/update-your-browser/";}
else if(langtwo == 'hy'){window.location.href="https://www.performasports.tv/update-your-browser/";}
else if(langtwo == 'az'){window.location.href="https://www.performasports.tv/update-your-browser/az/please-upgrade-your-browser.html";}
else if(langtwo == 'eu'){window.location.href="https://www.performasports.tv/update-your-browser/eu/please-upgrade-your-browser.html";}
else if(langtwo == 'be'){window.location.href="https://www.performasports.tv/update-your-browser/be/please-upgrade-your-browser.html";}
else if(langtwo == 'bn'){window.location.href="https://www.performasports.tv/update-your-browser/bn/please-upgrade-your-browser.html";}
else if(langtwo == 'bs'){window.location.href="https://www.performasports.tv/update-your-browser/bs/please-upgrade-your-browser.html";}
else if(langtwo == 'bg'){window.location.href="https://www.performasports.tv/update-your-browser/bg/please-upgrade-your-browser.html";}
else if(langtwo == 'ca'){window.location.href="https://www.performasports.tv/update-your-browser/ca/please-upgrade-your-browser.html";}
else if(langtwo == 'ce'){window.location.href="https://www.performasports.tv/update-your-browser/ceb/please-upgrade-your-browser.html";}
else if(langtwo == 'co'){window.location.href="https://www.performasports.tv/update-your-browser/co/please-upgrade-your-browser.html";}
else if(langtwo == 'hr'){window.location.href="https://www.performasports.tv/update-your-browser/hr/please-upgrade-your-browser.html";}
else if(langtwo == 'cs'){window.location.href="https://www.performasports.tv/update-your-browser/cs/please-upgrade-your-browser.html";}
else if(langtwo == 'da'){window.location.href="https://www.performasports.tv/update-your-browser/da/please-upgrade-your-browser.html";}
else if(langtwo == 'nl'){window.location.href="https://www.performasports.tv/update-your-browser/nl/please-upgrade-your-browser.html";}
else if(langtwo == 'eo'){window.location.href="https://www.performasports.tv/update-your-browser/eo/please-upgrade-your-browser.html";}
else if(langtwo == 'et'){window.location.href="https://www.performasports.tv/update-your-browser/et/please-upgrade-your-browser.html";}
else if(langtwo == 'fi'){window.location.href="https://www.performasports.tv/update-your-browser/fi/please-upgrade-your-browser.html";}
else if(langtwo == 'fr'){window.location.href="https://www.performasports.tv/update-your-browser/fr/please-upgrade-your-browser.html";}
else if(langtwo == 'fy'){window.location.href="https://www.performasports.tv/update-your-browser/fy/please-upgrade-your-browser.html";}
else if(langtwo == 'gl'){window.location.href="https://www.performasports.tv/update-your-browser/gl/please-upgrade-your-browser.html";}
else if(langtwo == 'ka'){window.location.href="https://www.performasports.tv/update-your-browser/ka/please-upgrade-your-browser.html";}
else if(langtwo == 'de'){window.location.href="https://www.performasports.tv/update-your-browser/de/please-upgrade-your-browser.html";}
else if(langtwo == 'el'){window.location.href="https://www.performasports.tv/update-your-browser/el/please-upgrade-your-browser.html";}
else if(langtwo == 'gu'){window.location.href="https://www.performasports.tv/update-your-browser/gu/please-upgrade-your-browser.html";}
else if(langtwo == 'ht'){window.location.href="https://www.performasports.tv/update-your-browser/ht/please-upgrade-your-browser.html";}
else if(langtwo == 'ha'){window.location.href="https://www.performasports.tv/update-your-browser/ha/please-upgrade-your-browser.html";}
else if(langtwo=='he' || langtwo=='iw'){window.location.href="https://www.performasports.tv/update-your-browser/he/please-upgrade-your-browser.html";}
else if(langtwo == 'hi'){window.location.href="https://www.performasports.tv/update-your-browser/hi/please-upgrade-your-browser.html";}
else if(langtwo == 'hm'){window.location.href="https://www.performasports.tv/update-your-browser/hmn/please-upgrade-your-browser.html";}
else if(langtwo == 'hu'){window.location.href="https://www.performasports.tv/update-your-browser/hu/please-upgrade-your-browser.html";}
else if(langtwo == 'is'){window.location.href="https://www.performasports.tv/update-your-browser/is/please-upgrade-your-browser.html";}
else if(langtwo == 'ig'){window.location.href="https://www.performasports.tv/update-your-browser/ig/please-upgrade-your-browser.html";}
else if(langtwo == 'id'){window.location.href="https://www.performasports.tv/update-your-browser/id/please-upgrade-your-browser.html";}
else if(langtwo == 'ga'){window.location.href="https://www.performasports.tv/update-your-browser/ga/please-upgrade-your-browser.html";}
else if(langtwo == 'it'){window.location.href="https://www.performasports.tv/update-your-browser/it/please-upgrade-your-browser.html";}
else if(langtwo == 'ja'){window.location.href="https://www.performasports.tv/update-your-browser/ja/please-upgrade-your-browser.html";}
else if(langtwo == 'jv'){window.location.href="https://www.performasports.tv/update-your-browser/jv/please-upgrade-your-browser.html";}
else if(langtwo == 'kn'){window.location.href="https://www.performasports.tv/update-your-browser/kn/please-upgrade-your-browser.html";}
else if(langtwo == 'kk'){window.location.href="https://www.performasports.tv/update-your-browser/kk/please-upgrade-your-browser.html";}
else if(langtwo == 'km'){window.location.href="https://www.performasports.tv/update-your-browser/km/please-upgrade-your-browser.html";}
else if(langtwo == 'rw'){window.location.href="https://www.performasports.tv/update-your-browser/rw/please-upgrade-your-browser.html";}
else if(langtwo == 'ko'){window.location.href="https://www.performasports.tv/update-your-browser/ko/please-upgrade-your-browser.html";}
else if(langtwo == 'ku'){window.location.href="https://www.performasports.tv/update-your-browser/ku/please-upgrade-your-browser.html";}
else if(langtwo == 'ky'){window.location.href="https://www.performasports.tv/update-your-browser/ky/please-upgrade-your-browser.html";}
else if(langtwo == 'lo'){window.location.href="https://www.performasports.tv/update-your-browser/lo/please-upgrade-your-browser.html";}
else if(langtwo == 'la'){window.location.href="https://www.performasports.tv/update-your-browser/la/please-upgrade-your-browser.html";}
else if(langtwo == 'lv'){window.location.href="https://www.performasports.tv/update-your-browser/lv/please-upgrade-your-browser.html";}
else if(langtwo == 'lt'){window.location.href="https://www.performasports.tv/update-your-browser/lt/please-upgrade-your-browser.html";}
else if(langtwo == 'lb'){window.location.href="https://www.performasports.tv/update-your-browser/lb/please-upgrade-your-browser.html";}
else if(langtwo == 'mk'){window.location.href="https://www.performasports.tv/update-your-browser/mk/please-upgrade-your-browser.html";}
else if(langtwo == 'mg'){window.location.href="https://www.performasports.tv/update-your-browser/mg/please-upgrade-your-browser.html";}
else if(langtwo == 'ms'){window.location.href="https://www.performasports.tv/update-your-browser/ms/please-upgrade-your-browser.html";}
else if(langtwo == 'ml'){window.location.href="https://www.performasports.tv/update-your-browser/ml/please-upgrade-your-browser.html";}
else if(langtwo == 'mt'){window.location.href="https://www.performasports.tv/update-your-browser/mt/please-upgrade-your-browser.html";}
else if(langtwo == 'mi'){window.location.href="https://www.performasports.tv/update-your-browser/mi/please-upgrade-your-browser.html";}
else if(langtwo == 'mr'){window.location.href="https://www.performasports.tv/update-your-browser/mr/please-upgrade-your-browser.html";}
else if(langtwo == 'mn'){window.location.href="https://www.performasports.tv/update-your-browser/mn/please-upgrade-your-browser.html";}
else if(langtwo == 'my'){window.location.href="https://www.performasports.tv/update-your-browser/my/please-upgrade-your-browser.html";}
else if(langtwo == 'ne'){window.location.href="https://www.performasports.tv/update-your-browser/ne/please-upgrade-your-browser.html";}
else if(langtwo == 'no'){window.location.href="https://www.performasports.tv/update-your-browser/no/please-upgrade-your-browser.html";}
else if(langtwo == 'ny'){window.location.href="https://www.performasports.tv/update-your-browser/ny/please-upgrade-your-browser.html";}
else if(langtwo == 'or'){window.location.href="https://www.performasports.tv/update-your-browser/or/please-upgrade-your-browser.html";}
else if(langtwo == 'ps'){window.location.href="https://www.performasports.tv/update-your-browser/ps/please-upgrade-your-browser.html";}
else if(langtwo == 'fa'){window.location.href="https://www.performasports.tv/update-your-browser/fa/please-upgrade-your-browser.html";}
else if(langtwo == 'pl'){window.location.href="https://www.performasports.tv/update-your-browser/pl/please-upgrade-your-browser.html";}
else if(langtwo == 'pt'){window.location.href="https://www.performasports.tv/update-your-browser/pt/please-upgrade-your-browser.html";}
else if(langtwo == 'pa'){window.location.href="https://www.performasports.tv/update-your-browser/pa/please-upgrade-your-browser.html";}
else if(langtwo == 'ro'){window.location.href="https://www.performasports.tv/update-your-browser/ro/please-upgrade-your-browser.html";}
else if(langtwo == 'ru'){window.location.href="https://www.performasports.tv/update-your-browser/ru/please-upgrade-your-browser.html";}
else if(langtwo == 'sm'){window.location.href="https://www.performasports.tv/update-your-browser/sm/please-upgrade-your-browser.html";}
else if(langtwo == 'gd'){window.location.href="https://www.performasports.tv/update-your-browser/gd/please-upgrade-your-browser.html";}
else if(langtwo == 'sr'){window.location.href="https://www.performasports.tv/update-your-browser/sr/please-upgrade-your-browser.html";}
else if(langtwo == 'st'){window.location.href="https://www.performasports.tv/update-your-browser/st/please-upgrade-your-browser.html";}
else if(langtwo == 'sn'){window.location.href="https://www.performasports.tv/update-your-browser/sn/please-upgrade-your-browser.html";}
else if(langtwo == 'sd'){window.location.href="https://www.performasports.tv/update-your-browser/sd/please-upgrade-your-browser.html";}
else if(langtwo == 'si'){window.location.href="https://www.performasports.tv/update-your-browser/si/please-upgrade-your-browser.html";}
else if(langtwo == 'sk'){window.location.href="https://www.performasports.tv/update-your-browser/sk/please-upgrade-your-browser.html";}
else if(langtwo == 'sl'){window.location.href="https://www.performasports.tv/update-your-browser/sl/please-upgrade-your-browser.html";}
else if(langtwo == 'so'){window.location.href="https://www.performasports.tv/update-your-browser/so/please-upgrade-your-browser.html";}
else if(langtwo == 'es'){window.location.href="https://www.performasports.tv/update-your-browser/es/please-upgrade-your-browser.html";}
else if(langtwo == 'su'){window.location.href="https://www.performasports.tv/update-your-browser/su/please-upgrade-your-browser.html";}
else if(langtwo == 'sw'){window.location.href="https://www.performasports.tv/update-your-browser/sw/please-upgrade-your-browser.html";}
else if(langtwo == 'sv'){window.location.href="https://www.performasports.tv/update-your-browser/sv/please-upgrade-your-browser.html";}
else if(langtwo == 'tl'){window.location.href="https://www.performasports.tv/update-your-browser/tl/please-upgrade-your-browser.html";}
else if(langtwo == 'tg'){window.location.href="https://www.performasports.tv/update-your-browser/tg/please-upgrade-your-browser.html";}
else if(langtwo == 'ta'){window.location.href="https://www.performasports.tv/update-your-browser/ta/please-upgrade-your-browser.html";}
else if(langtwo == 'tt'){window.location.href="https://www.performasports.tv/update-your-browser/tt/please-upgrade-your-browser.html";}
else if(langtwo == 'te'){window.location.href="https://www.performasports.tv/update-your-browser/te/please-upgrade-your-browser.html";}
else if(langtwo == 'th'){window.location.href="https://www.performasports.tv/update-your-browser/th/please-upgrade-your-browser.html";}
else if(langtwo == 'tr'){window.location.href="https://www.performasports.tv/update-your-browser/tr/please-upgrade-your-browser.html";}
else if(langtwo == 'tk'){window.location.href="https://www.performasports.tv/update-your-browser/tk/please-upgrade-your-browser.html";}
else if(langtwo == 'uk'){window.location.href="https://www.performasports.tv/update-your-browser/uk/please-upgrade-your-browser.html";}
else if(langtwo == 'ur'){window.location.href="https://www.performasports.tv/update-your-browser/ur/please-upgrade-your-browser.html";}
else if(langtwo == 'ug'){window.location.href="https://www.performasports.tv/update-your-browser/ug/please-upgrade-your-browser.html";}
else if(langtwo == 'uz'){window.location.href="https://www.performasports.tv/update-your-browser/uz/please-upgrade-your-browser.html";}
else if(langtwo == 'vi'){window.location.href="https://www.performasports.tv/update-your-browser/vi/please-upgrade-your-browser.html";}
else if(langtwo == 'cy'){window.location.href="https://www.performasports.tv/update-your-browser/cy/please-upgrade-your-browser.html";}
else if(langtwo == 'xh'){window.location.href="https://www.performasports.tv/update-your-browser/xh/please-upgrade-your-browser.html";}
else if(langtwo == 'yi'){window.location.href="https://www.performasports.tv/update-your-browser/yi/please-upgrade-your-browser.html";}
else if(langtwo == 'yo'){window.location.href="https://www.performasports.tv/update-your-browser/yo/please-upgrade-your-browser.html";}
else if(langtwo == 'zu'){window.location.href="https://www.performasports.tv/update-your-browser/zu/please-upgrade-your-browser.html";}

else if(lang == 'haw'){window.location.href="https://www.performasports.tv/update-your-browser/haw/please-upgrade-your-browser.html";}
//else English
 else{window.location.href="https://www.performasports.tv/update-your-browser/en/please-upgrade-your-browser.html";}}
